experiment_name: "Wildfire_Greedy_Exp02"
run_mode: "simulate"   # Options: "simulate", "visualize_only"
data:
  directory: "data/Sub40x40/grids/Grids1"
  num_time_steps: 8
simulation:
  detection_threshold: 0.5
deployment:
  algorithm: "Greedy"        # Options: Greedy, ILP, Genetic, ActiveLearning
  num_sensors: 5
  sensor_radius: 2.0
logs:
  output_directory: "logs"
dashboard:
  enabled: true
initial_forest_image: "data/Sub40x40/InitialForest.png"
burn_probability:
  file: "" #"data/Sub40x40/Stats/BProb.csv"    # Provide path to a burn probability CSV if available; leave empty to generate randomly.
  decay_factor: 0.9

